#!/usr/bin/env node
// Generates styles/tokens.css from design-system/sumuk.tokens.json (W3C DTCG 2025.10).
//
// The JSON is vendored from inzeum-platform-app/apps/mobile/design-system/tokens/sumuk.tokens.json,
// pinned to a Sumuk version (see $extensions.inzeum.version). The site never hand-copies a hex:
// every colour, radius, space, size and curve on inzeum.com comes through this file, so a Sumuk
// bump is a pin bump plus a reviewable diff of tokens.css.
//
//   npm run tokens          # regenerate
//   npm run tokens:check    # CI: fail if tokens.css is stale
//
// Emits:
//   :root            palette ramps, the dark (default) role map, geometry, motion
//   .ground-hanji    the light role map (theme.hanji) as a remap of the same role names,
//                    plus the site-local additions listed in SITE_LOCAL below.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(here, '../design-system/sumuk.tokens.json')
const OUT = resolve(here, '../styles/tokens.css')
const check = process.argv.includes('--check')

const tokens = JSON.parse(readFileSync(SRC, 'utf8'))
const version = tokens.$extensions?.inzeum?.version ?? 'unknown'

// ---------- helpers ----------
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function getPath(path) {
  return path.split('.').reduce((o, k) => (o == null ? undefined : o[k]), tokens)
}

// Resolve a $value that may be a "{ref.path}" string, a hex string, a colour object,
// a dimension/duration object, a number, or a cubicBezier array.
function resolveValue(v) {
  if (typeof v === 'string') {
    const m = v.match(/^\{(.+)\}$/)
    if (m) {
      const node = getPath(m[1])
      if (!node || node.$value === undefined) throw new Error(`Unresolved reference ${v}`)
      return resolveValue(node.$value)
    }
    return v
  }
  if (Array.isArray(v)) return `cubic-bezier(${v.join(', ')})`
  if (v && typeof v === 'object') {
    if ('hex' in v) {
      const a = v.alpha ?? 1
      if (a >= 1) return v.hex.toUpperCase()
      const [r, g, b] = v.components.map((c) => Math.round(c * 255))
      return `rgb(${r} ${g} ${b} / ${a})`
    }
    if ('unit' in v) return `${v.value}${v.unit}`
  }
  return String(v)
}

const lines = []
const emit = (name, value, comment) =>
  lines.push(`  --${name}: ${value};${comment ? ` /* ${comment} */` : ''}`)

// ---------- :root ----------
lines.push(`/* GENERATED by scripts/build-tokens.mjs from design-system/sumuk.tokens.json — do not edit. */`)
lines.push(`/* 수묵 Sumuk ${version} · ADR ${tokens.$extensions?.inzeum?.adr ?? '?'} · https://github.com/Inzeum-ai/inzeum-platform-app */`)
lines.push(`:root {`)
lines.push(`  color-scheme: dark;`)

lines.push(`  /* palette — raw ramps; screens compose roles, never these */`)
for (const [family, ramp] of Object.entries(tokens.palette)) {
  if (family.startsWith('$')) continue
  for (const [step, t] of Object.entries(ramp)) {
    if (step.startsWith('$')) continue
    emit(`${family}-${step}`, resolveValue(t.$value))
  }
}

lines.push(`  /* roles — dark (default) */`)
for (const [role, t] of Object.entries(tokens.color)) {
  if (role.startsWith('$')) continue
  emit(kebab(role), resolveValue(t.$value))
}

lines.push(`  /* geometry */`)
for (const [k, t] of Object.entries(tokens.radius)) if (!k.startsWith('$')) emit(`radius-${k}`, resolveValue(t.$value))
for (const [k, t] of Object.entries(tokens.space)) if (!k.startsWith('$')) emit(`space-${k}`, resolveValue(t.$value))
for (const [k, t] of Object.entries(tokens.size)) if (!k.startsWith('$')) emit(`size-${kebab(k)}`, resolveValue(t.$value))
for (const [k, t] of Object.entries(tokens.zIndex)) if (!k.startsWith('$')) emit(`z-${k}`, resolveValue(t.$value))
for (const [k, t] of Object.entries(tokens.opacity)) if (!k.startsWith('$')) emit(`opacity-${k}`, resolveValue(t.$value))

lines.push(`  /* motion — one family of curves, breathing pace */`)
for (const [k, t] of Object.entries(tokens.motion.easing)) if (!k.startsWith('$')) emit(`ease-${k}`, resolveValue(t.$value))
for (const group of ['settle', 'press', 'sheet', 'breath']) {
  const g = tokens.motion[group]
  if (!g) continue
  for (const [k, t] of Object.entries(g)) {
    if (k.startsWith('$') || t?.$value === undefined) continue
    emit(`motion-${group}-${kebab(k)}`, resolveValue(t.$value))
  }
}
lines.push(`}`)

// ---------- .ground-hanji ----------
const hanji = tokens.theme?.hanji
if (hanji) {
  lines.push(``)
  lines.push(`/* 한지 — the light role map. Same role names remapped onto the same palette (theme.hanji). */`)
  lines.push(`.ground-hanji {`)
  lines.push(`  color-scheme: light;`)
  for (const [role, t] of Object.entries(hanji)) {
    if (role.startsWith('$')) continue
    emit(kebab(role), resolveValue(t.$value))
  }
  // Site-local additions — each carries its reason, per governance §3 "off-scale carries a comment".
  const SITE_LOCAL = [
    ['text-muted', '#6F6656', 'site-local: theme.hanji notes paper.500/600 are hint-only on paper50 (≈3.3–3.9:1); this step measures 5.6:1 for meta text'],
    ['text-faint', '#887E6B', 'site-local: hints only, never running text (3.9:1)'],
  ]
  for (const [name, value, why] of SITE_LOCAL) emit(name, value, why)
  lines.push(`}`)
}

const css = lines.join('\n') + '\n'

if (check) {
  let current = ''
  try { current = readFileSync(OUT, 'utf8') } catch {}
  if (current !== css) {
    console.error('styles/tokens.css is stale — run `npm run tokens`')
    process.exit(1)
  }
  console.log('tokens.css is current')
} else {
  writeFileSync(OUT, css)
  console.log(`wrote ${OUT} (Sumuk ${version})`)
}
